### ISSUE TITLE
Android: segmentation with task API

### ISSUE THREAD

**Issue by margaretmz** [margaretmz/segmentation-style-transfer#15]
Segmentation on Android with the new task API:

- ImageSegmenter documentation: https://www.tensorflow.org/lite/inference_with_metadata/task_library/image_segmenter
- Khanh's sample:  https://github.com/khanhlvg/tflite-task-library-demo/blob/master/app/src/main/java/com/khanhlvg/taskapidemo/ImageSegmenterActivity.java

**Comment by farmaker47** [comment]
I found some time to change a little bit Khanh's [project](https://github.com/khanhlvg/tflite-task-library-demo) to demonstrate how we are going to take the person only from photo:
![Screenshot](https://user-images.githubusercontent.com/26084498/93374804-e8d3d600-f85f-11ea-9054-bfdf15681d4f.jpg)

@khanhlvg if you like the result please advise me if you want to make a pull request at your github project to have this effect also in your demo.

I will continue with Camera X implementation the next days.

**Comment by khanhlvg** [comment]
Sure, please send the pull request :)

**Comment by farmaker47** [comment]
I used CameraX and Task library to a project similar with Cartoonizer. Below a screenshot with myself cropped:
![Screenshot_2020-09-20-09-05-53-833_com tflite whitebox_cartoon_gan](https://user-images.githubusercontent.com/26084498/93704927-4b0f2e00-fb21-11ea-9b40-4949f5e8fb21.jpg)
Inference time for result is 3 seconds...fair enough I think.

WDYT?

**Comment by farmaker47** [comment]
I have uploaded project to a [github repository](https://github.com/farmaker47/Segmentation_and_Style_Transfer). If you have time check it and tell me WDYT.
Thanks.

@khanhlvg I want to ask if Task Library for Segmentation supports other delegates than CPU and/or more threads and XNNPACK to speed up the process. Is there a solution for faster results?

**Comment by farmaker47** [comment]
I have changed the [project](https://github.com/farmaker47/Segmentation_and_Style_Transfer) with:
- Koin DI
- MVVM
- Possibility to get picture from gallery and perform Segmantation

I will continue with the Style transfer implementation.

Thanks

**Comment by khanhlvg** [comment]
@farmaker47 Unfortunately hardware accelerators and number of threads are not configurable in Task API at this moment. I've filed a feature request to the team as these are very important features.
